# Generated by Django 3.1.2 on 2020-10-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('cidade', models.CharField(blank=True, max_length=50)),
                ('bairro', models.CharField(blank=True, max_length=50)),
                ('rua', models.CharField(blank=True, max_length=50)),
                ('numero', models.IntegerField(blank=True)),
                ('login', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=50)),
                ('data_criacao', models.DateField()),
            ],
        ),
    ]
