# Generated by Django 3.1.2 on 2020-10-08 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0003_pedido_cardapios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
