# Generated by Django 3.1.1 on 2020-10-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0005_auto_20201011_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_criacao',
            field=models.DateField(null=True),
        ),
    ]
