# Generated by Django 3.1.1 on 2020-10-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0006_auto_20201011_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
