# Generated by Django 3.1.1 on 2020-10-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0007_auto_20201012_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
