# Generated by Django 3.1.1 on 2020-10-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0010_auto_20201013_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='urlImg',
        ),
        migrations.AddField(
            model_name='cardapio',
            name='img',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
