# Generated by Django 3.1.1 on 2020-10-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0011_auto_20201025_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='img',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
