# Generated by Django 3.1.1 on 2020-10-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0012_auto_20201026_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cardapios',
            field=models.ManyToManyField(blank=True, to='pizzaria.Cardapio'),
        ),
    ]
