# Generated by Django 3.1.2 on 2020-10-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaria', '0002_cardapio_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cardapios',
            field=models.ManyToManyField(to='pizzaria.Cardapio'),
        ),
    ]
